version: "3"
services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    tty: true
    # volumes:
    #   - ./server:/go/src/server
    ports:
      - "18888:18888"
    working_dir: /go/src/server
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    tty: true
    volumes:
      - ./client:/go/src/client
    ports:
      - "8080:8080"
    working_dir: /go/src/client
